
create table users (
    id int8 generated by default as identity,
    email varchar(255) not null,
    password varchar(255) not null,
    reg_time timestamp not null,
    code varchar(255) null,
    is_enabled boolean,
    primary key (id)
);

create table roles (
    id int8 generated by default as identity,
    role_name varchar(255) not null,
    primary key (id)
);

insert into roles(role_name) values ('ROLE_ADMIN');
insert into roles(role_name) values ('ROLE_USER');

create table users_roles (
    id int8 generated by default as identity,
    user_id int8 not null,
    role_id int8 not null,
    primary key (user_id, role_id),
    constraint fk_users foreign key (user_id) references users (id),
    constraint fk_roles foreign key (role_id) references roles (id)
);


